name: Production build and publish package

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: AWSsecurity group test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 18.x ]

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Add public IP to AWS security group
        uses: sohelamin/aws-security-group-add-ip-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'
          aws-security-group-id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
          port: '22'
          to-port: '22'
          protocol: 'tcp'
          description: 'GitHub Action'

