name: GitHub Actions Demo
on:
  push:
    branches: [ master ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: useless checks
        run: pwd
      - name: Listing contents
        run: ls -lah
      - name: check node version
        run: node --version
      